### ISSUE TITLE
Диаграммы

### ISSUE THREAD

**Issue by VVaulin** [VVaulin/kursa4#6]
### Архитектурные диаграммы продукта:

- [x] Архитектурная диаграмма (в соответствии с архитектурой продукта)
- [x] Функциональная диаграмма UML
- [x] Диаграмма последовательности UML (для одной выбранной ключевой функции)
- [x] Концептуальная модель БД

**Comment by kseniashv** [comment]
Диаграммы созданы, ниже прикреплены 
![Архитектурная диаграмма](https://github.com/VVaulin/kursa4/assets/150257757/f809a113-9acd-42f2-9481-024597652d32)
![Диаграмма последовательности](https://github.com/VVaulin/kursa4/assets/150257757/5fdf1372-d670-4686-994e-26fe650e9586)
![Концептуальная модель](https://github.com/VVaulin/kursa4/assets/150257757/b3402031-94e3-4659-ba1a-f267a3af9f3f)
![Функциональная диаграмма](https://github.com/VVaulin/kursa4/assets/150257757/83dc03db-c8ad-4c99-8e0f-1485b655f011)
